import { colors } from '../theme/muiThemeVariables.ts';
import { writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import path from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Convert camelCase to kebab-case
export const camelToKebab = (str: string) => {
  return str.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();
};

// Helper to group colors by prefix and shades
export const groupColors = (colorObj: Record<string, string>) => {
  const groups: Record<string, Record<string, string>> = {};
  Object.entries(colorObj).forEach(([key, value]) => {
    const match = key.match(/^([a-zA-Z]+)([A-Z][a-zA-Z]+|\d+)?$/);
    if (match) {
      let group = match[1];
      let shade = match[2];
      group = camelToKebab(group);
      if (!shade || shade === 'base') {
        shade = 'base';
      }
      if (!groups[group]) groups[group] = {};
      groups[group][shade] = value;
    }
  });
  return groups;
};

const grouped = groupColors(colors);

// Convert grouped colors to SCSS map format
// Example: $ta-colors: (primary: (base: '#1c9ebe', 50: '#eefbfd', ...)
export const toScssMap = (name: string, obj: Record<string, Record<string, string>>) => {
  let scss =
    '// Do not edit this file directly.\n' +
    '// This file is auto-generated from the src/theme/muiThemeVariables.ts using src/utils/generateScssVariables.ts\n' +
    '// Colors ---> usage => background-color: map.get($ta-colors, primary, 300);\n' +
    `$${name}: (\n`;
  for (const group in obj) {
    scss += `  ${group}: (\n`;
    for (const shade in obj[group]) {
      scss += `    ${shade}: ${obj[group][shade]},\n`;
    }
    scss += `  ),\n`;
  }
  scss += `);\n`;
  return scss;
};

const scss = toScssMap('ta-colors', grouped);

writeFileSync(path.resolve(__dirname, '../styles/abstract/_color-variables.scss'), scss);
